### ISSUE TITLE
[Bug]: instagrpc always call type stream when using grpc.UnknownServiceHandler

### ISSUE THREAD

**Issue by vtolstov** [instana/go-sensor#967] opened 2024-12-04 19:32 UTC
### Problem Description

i have only unary calls with my client-servers but instana ui always show that 
Call Type stream

### Go Version

go1.23

### go.mod

```shell
github.com/instana/go-sensor/instrumentation/instagrpc v1.29.0
google.golang.org/grpc v1.68.0
```

### go env

```shell
vtolstov@msk-1659tk customer-grpc % go env
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/vtolstov/Library/Caches/go-build'
GOENV='/Users/vtolstov/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE='bitbucket.sberbank.kz'
GOMODCACHE='/Users/vtolstov/go/pkg/mod'
GOOS='darwin'
GOPATH='/Users/vtolstov/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.23.3/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.23.3/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.23.3'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/Users/vtolstov/Library/Application Support/go/telemetry'
GCCGO='gccgo'
GOARM64='v8.0'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='xxxx
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/ym/j5bjj8cn1kn5gmyh6vrdqs580000gn/T/go-build3100268058=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

**Comment by nithinputhenveettil** [comment] 2024-12-04 23:46
@vtolstov Thank you for your report. We will look into the issue and get back to you shortly.

**Comment by Angith** [comment] 2024-12-06 10:41
Hi @vtolstov 

I have tried to reproduce this issue on my end, but I was not able to. I’ve created a sample gRPC server and client, instrumented with `Instagrpc`, using the same versions of the gRPC package and Instagrpc that you specified. In the Instana UI, the call type is correctly displayed as `unary`. (I have attached a screenshot here.)

<img width="489" alt="unary-server-destination" src="https://github.com/user-attachments/assets/74c82a16-732a-4dd9-9d80-26190533e6ac">

To help me investigate further, could you please provide a minimal reproducible example of your code that demonstrates the issue?

**Comment by vtolstov** [comment] 2024-12-09 23:08
may be i'm understand why i have this issue, some of my methods using grpc.UnknownServiceHandler and for such case instagrpc always think that this method stream and not unary.

How can i deal with this? (i need to have grpc.UnknownServiceHandler to be able to handle unknown methods).

Does it possible to overwrite tag Call Type ?

**Comment by Angith** [comment] 2024-12-10 11:53
Hi @vtolstov 

Regarding the behavior you described:

> _Some of my methods use grpc.UnknownServiceHandler, and in such cases, Instagrpc always identifies the method as a stream instead of unary._

This behavior is expected because the gRPC library internally [treats](https://github.com/grpc/grpc-go/blob/master/server.go#L520-L530) UnknownServiceHandler as a StreamHandler.

> _Is it possible to overwrite the call type tag?_

Unfortunately, it is not currently possible to overwrite the call type. The span is created and finalized within the interceptor, which makes it impossible to modify the tag of the span afterward.

To better assist you, could you please explain your specific requirements with a verifiable example? This will help us better understand your use case and explore potential solutions more effectively.

**Comment by vtolstov** [comment] 2024-12-11 07:24
i'm dynamically add/remove methods to service

**Comment by Angith** [comment] 2024-12-17 06:16
> Hi @vtolstov, What call type do you expect in the case of `grpc.UnknownServiceHandler`?

@vtolstov A gentle reminder.

**Comment by Angith** [comment] 2024-12-20 09:05
Hi @vtolstov ,

I am closing this issue for now.

The current observed behavior is as expected and not a bug. Since `grpc.UnknownServiceHandler` is treated as a `StreamHandler` in gRPC the call type will be `stream`.

If you have any concerns, please feel free to reopen this issue with your requirement and a reproducible example.

Thank you.

**Closed by Angith** 2024-12-20 09:05 UTC
